markdown: kramdown

environment: local
baseurl: /
version: 0.1.6

kramdown:
  auto_ids: false

source: ../src
destination: ../_site

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

permalink: /:year/:month/:day/:title/

# Allow future dates posts to be published
future: true

collections:
  translations:
    output: true
    permalink: /:path/

keep_files:
  - css
  - js

exclude:
  - sass
  - js
